require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  EnabledByDefault: true
  ExtraDetails: true
  Exclude:
    - db/schema.rb
    - node_modules/**/*
    - vendor/**/*

Bundler/GemComment:
  Enabled: false

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/DotPosition:
  # When the dot is trailing, you can copy multiple lines of code and paste them straight into
  # irb/pry/rails-console.
  EnforcedStyle: trailing

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/ExtraSpacing:
  AllowForAlignment: false

Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Max: 100

Layout/MultilineAssignmentLayout:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineMethodDefinitionBraceLayout:
  EnforcedStyle: new_line

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Lint/ConstantResolution:
  inherit_mode:
    merge:
      - Only
  Only:
    - Rubocop

Naming/MethodParameterName:
  inherit_mode:
    merge:
      - AllowedNames
  AllowedNames:
    - as

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - config/routes.rb

Metrics/MethodLength:
  Max: 20

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/SkipsModelValidations:
  Exclude:
    - db/migrate/**/*

Rails/UnknownEnv:
  Environments:
    - development
    - production
    - staging
    - test

RSpec/AlignLeftLetBrace:
  Enabled: false

RSpec/AlignRightLetBrace:
  Enabled: false

RSpec/ContextWording:
  Prefixes:
    - for
    - given
    - in
    - when
    - with
    - without

RSpec/ImplicitExpect:
  EnforcedStyle: should

RSpec/ExampleLength:
  Max: 5

RSpec/ExpectChange:
  EnforcedStyle: block

RSpec/LetSetup:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 5

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

# RSpec already tells us that tests are pending
RSpec/Pending:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ConstantVisibility:
  Enabled: false

Style/Copyright:
  Enabled: false

Style/DisableCopsWithinSourceCodeDirective:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/InlineComment:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/MissingElse:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/RescueStandardError:
  EnforcedStyle: implicit

# Many libraries, such as jwt and annotate_models, require passing arguments Hashes
# with String keys.
Style/StringHashKeys:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/YodaCondition:
  Enabled: false
